#!/bin/bash

# install.sh
# Installer for Dell Optiplex Intelligent Fan Control (DeltaFlow)
# Author: KaltWulx

if [[ $EUID -ne 0 ]]; then
   echo "Error: This script must be run as root."
   exit 1
fi

# Paths
INSTALL_DIR="/usr/local/bin"
CONFIG_FILE="/etc/fan_control.conf"
SERVICE_FILE="/etc/systemd/system/fan_control.service"
SCRIPT_NAME="fan_control.sh"
CALIB_NAME="fan_calibration.sh"

echo "=================================================="
echo "      DeltaFlow Installer - Dell Fan Control      "
echo "=================================================="

# 1. Verify source files
if [[ ! -f "$SCRIPT_NAME" ]]; then
    echo "Error: $SCRIPT_NAME not found in current directory."
    exit 1
fi

# 2. Install Scripts
echo "--> Installing scripts to $INSTALL_DIR..."
cp "$SCRIPT_NAME" "$INSTALL_DIR/$SCRIPT_NAME"
chmod +x "$INSTALL_DIR/$SCRIPT_NAME"
echo "    $SCRIPT_NAME installed."

if [[ -f "$CALIB_NAME" ]]; then
    cp "$CALIB_NAME" "$INSTALL_DIR/$CALIB_NAME"
    chmod +x "$INSTALL_DIR/$CALIB_NAME"
    echo "    $CALIB_NAME installed."
fi

# 3. Create Systemd Service (Install first so calibration can restart it)
echo "--> Creating systemd service at $SERVICE_FILE..."
cat <<EOF > "$SERVICE_FILE"
[Unit]
Description=Dell Optiplex Intelligent Fan Control (DeltaFlow)
After=syslog.target module-load.service
ConditionPathExists=$INSTALL_DIR/$SCRIPT_NAME

[Service]
Type=simple
ExecStart=$INSTALL_DIR/$SCRIPT_NAME
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=fan_control

[Install]
WantedBy=multi-user.target
EOF

# Reload daemon to recognize the new service
systemctl daemon-reload
systemctl enable fan_control.service

# 4. Calibration / Configuration
echo ""
echo "--------------------------------------------------"
read -p "Do you want to run the calibration tool now? (Recommended) [y/N]: " run_calib

if [[ "$run_calib" =~ ^[yY]$ ]]; then
    echo "--> Launching calibration tool..."
    "$INSTALL_DIR/$CALIB_NAME"
else
    # Create Default Config ONLY if it doesn't exist and user skipped calibration
    if [[ ! -f "$CONFIG_FILE" ]]; then
        echo "--> Creating default configuration at $CONFIG_FILE..."
        cat <<EOF > "$CONFIG_FILE"
# /etc/fan_control.conf
# Default configuration for DeltaFlow
# Generated by install.sh

# Energy profile: "balanced" or "performance"
PROFILE="balanced"

# Temperature Thresholds (Celsius)
MIN_TEMP=30
MAX_TEMP=60
CRITICAL_TEMP=80

# PWM Limits (0-255)
MIN_PWM=60
MAX_PWM=255

# Custom Tuning
# The PWM value where noise becomes annoying.
# Used by the 'balanced' profile as a soft limit.
QUIET_MAX_PWM=165

# Advanced Settings
TEMP_HYSTERESIS=2
SLEW_RATE_LIMIT=15
EOF
        echo "    Default config created."
    else
        echo "--> Configuration file already exists (skipping default creation)."
    fi
    
    # Start service manually since calibration didn't do it
    echo "--> Starting service..."
    systemctl restart fan_control.service
fi

# 5. Verification
echo ""
if systemctl is-active --quiet fan_control.service; then
    echo "SUCCESS: Service is running."
else
    echo "WARNING: Service failed to start. Check logs."
fi

echo ""
echo "=================================================="
echo "Installation Complete!"
echo "--------------------------------------------------"
echo "Commands:"
echo "  Status:    systemctl status fan_control.service"
echo "  Logs:      $INSTALL_DIR/$SCRIPT_NAME --log"
echo "  Calibrate: sudo $INSTALL_DIR/$CALIB_NAME"
echo "  Help:      $INSTALL_DIR/$SCRIPT_NAME --help"
echo "=================================================="
